### PR TITLE
Containerized CI and added reusable workflow capability 

### PR DESCRIPTION
**Pull request by mlee03**
**Description**
In this PR, the CI workflow is changed to run in a [container](https://github.com/orgs/NOAA-GFDL/packages/container/package/miniforge). The container is built from a base miniforge container. GNU compilers, netCDF and HDF5 libraries, and MPICH have been installed. The default python version is set to 3.11.7. 

The workflow yaml file has also been edited to allow reusable workflows.  PySHiELD translate tests can now be triggered from PyFV3 and NDSL repositories.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] Targeted model, if this change was triggered by a model need/shortcoming

### CODE REVIEW

**Review by fmalatino — DISMISSED** [review]
lgtm

**Review by xyuan — DISMISSED** [review]

**Review by oelbert — DISMISSED** [review]
LGTM

**Comment by mlee03** [comment]
Sorry!  I pushed to the reusable workflow changes to the wrong branch and now it's in this branch. It should work!  I think this PR needs to be re-approved.

**Review by fmalatino — CHANGES_REQUESTED** [review]
numpy needs to be pinned to 1.26.4, then should be good to merge

**Comment by mlee03** [comment]
Following your suggestion, it has been changed.

**Review by fmalatino — COMMENTED** [review]
It also appears that the `lint` process will now require a python 3.11.7 base as well. Then it should be good to merge.

**Review by fmalatino — APPROVED** [review]
lgtm

**Pull request merged**
